# Generated by Django 4.1.2 on 2023-04-08 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titre', models.CharField(max_length=100)),
                ('siege', models.CharField(max_length=100)),
                ('Image', models.ImageField(upload_to='restaurants/')),
                ('telephone', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('description', models.CharField(max_length=100)),
                ('restaurateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vente.restaurateur')),
            ],
        ),
    ]
