# Generated by Django 4.1.2 on 2023-04-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vente', '0002_produit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name2', models.CharField(max_length=30)),
                ('email2', models.EmailField(blank=True, max_length=254)),
                ('phone2', models.CharField(max_length=20)),
                ('suject2', models.CharField(max_length=30)),
                ('description2', models.TextField(default='votre probleme')),
            ],
        ),
    ]
