# Generated by Django 4.1.2 on 2023-04-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vente', '0003_commentaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='suject2',
            field=models.CharField(max_length=50),
        ),
    ]
