# Generated by Django 4.1.2 on 2023-04-13 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vente', '0009_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
